sudo: false
branches:
    only:
        - /.*/
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
    - pip install coveralls
    - pip install tox-travis
cache: pip
script:
    - coverage run --source src tox
after_success:
    coveralls
